codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 50%
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
