version: '3.9'

services:
  nlp:
    image: nlp-web:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - db
      - elastic

    ports:
      - "0.0.0.0:8000:8000"

  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./db_config/create_user_table.sql:/docker-entrypoint-initdb.d/cut.sql
      - ./db_config/create_post_table.sql:/docker-entrypoint-initdb.d/cut2.sql
    ports:
      - "5432:5432"

  elastic:
    image: elasticsearch:7.14.1
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl' , '-f', 'http://localhost:9200/_cluster/health/']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  data01:
    driver: local
