version: '3.9'

services:
  nlp:
    image: nlp-web:latest
    build:
      context: .
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
    volumes:
      - ./src:/app
    depends_on:
      - db
      - elastic

    ports:
      - "0.0.0.0:8000:8000"

  db:
    image: postgres:12
    volumes:
      - ./db_config/create_user_table.sql:/docker-entrypoint-initdb.d/cut.sql
      - ./db_config/create_post_table.sql:/docker-entrypoint-initdb.d/cut2.sql
    ports:
      - "5432:5432"

  elastic:
    image: elasticsearch:7.10.1
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ['CMD', 'curl' , '-f', 'http://localhost:9200/_cluster/health/']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  data01:
    driver: local
