version: '3.9'

services:
  app:
    image: nlp-web:latest
    build:
      context: .
    env_file:
      - .env
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
    volumes:
      - ./src:/app

    ports:
      - "8000:8000"
