version: '3.9'

services:
  nlp:
    image: nlp-web:latest
    build:
      context: .
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_PORT=8000
      - FLASK_ENV=development
    volumes:
      - ./src:/app
    depends_on:
      - db

    ports:
      - "0.0.0.0:8000:8000"

  db:
    image: postgres:12
    volumes:
      - ./db_config/create_user_table.sql:/docker-entrypoint-initdb.d/cut.sql
      - ./db_config/create_post_table.sql:/docker-entrypoint-initdb.d/cut2.sql
    ports:
      - "5432:5432"

volumes:
  data01:
    driver: local
