---
name: commit

on:
  push:

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make install-front build-front build-test
      - name: test
        run: make test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          path_to_write_report: ./coverage/index.html
