---
name: commit

on:
  push:

jobs:
  pylint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build-test
      - name: lint
        run: make lint

  test:
    name: Pytest
    runs-on: ubuntu-latest
    needs: pylint
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make install-front build-front build-test
      - name: test
        run: make test-cov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          files: ./coverage.xml

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: TEST_ENV=CI make build install-front build-front up
      - name: run cypress
        run: TEST_ENV=CI make test-front
