---
name: Publish NLP Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for docker iamge'
        required: true

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make install-front build-front build
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GHCR_PUBLISH }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GitHub Container Registry
        run: |
          docker tag nlp-web:latest ghcr.io/${{ github.repository_owner }}/nlp-web:${{ github.event.inputs.tag_name }}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/nlp-web:${{ github.event.inputs.tag_name }}
          docker push $IMAGE_ID
