---
name: Offline Update

on:
  workflow_dispatch:

jobs:
  update-s3:
    name: Upload new offline pages to S3 Bucket
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: TEST_ENV=CI make build-test install-front build-front
      - name: create offline files
        run: TEST_ENV=CI make build-static
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload
        run: |
          aws s3 cp src/app/static/offline/bundle.js s3://offline.kamutiv.com/bundle.js
          aws s3 cp src/app/static/react.css s3://offline.kamutiv.com/react.css
          aws s3 cp src/app/static/offline/index s3://offline.kamutiv.com/index --content-type "text/html"
          aws s3 cp src/app/static/offline/kumia s3://offline.kamutiv.com/kumia --content-type "text/html"
          aws s3 cp src/app/static/offline/natural s3://offline.kamutiv.com/natural --content-type "text/html"
          aws s3 cp src/app/static/offline/language s3://offline.kamutiv.com/language --content-type "text/html"
          aws s3 cp src/app/static/offline/processing s3://offline.kamutiv.com/processing --content-type "text/html"
